In [226]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [227]:
sentences = [
    'The glass of milk',
    'The glass of juice',
    'The cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understand the meaning of words',
    'Your videos are good'
]

In [228]:
sentences

['The glass of milk',
 'The glass of juice',
 'The cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'Your videos are good']

In [229]:
vocab_size = 10000
embedding_dim = 10
max_sequence_length = 8

In [232]:
onehot_repr = [one_hot(sentence, vocab_size) for sentence in sentences]
onehot_repr

[[3846, 4777, 69, 3268],
 [3846, 4777, 69, 2276],
 [3846, 5557, 69, 6765],
 [8961, 8692, 3975, 5272, 5029],
 [8961, 8692, 3975, 5272, 7841],
 [1775, 3846, 9337, 69, 7685],
 [4850, 6366, 7157, 5272]]

In [233]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=max_sequence_length)
print(embedded_docs)

[[   0    0    0    0 3846 4777   69 3268]
 [   0    0    0    0 3846 4777   69 2276]
 [   0    0    0    0 3846 5557   69 6765]
 [   0    0    0 8961 8692 3975 5272 5029]
 [   0    0    0 8961 8692 3975 5272 7841]
 [   0    0    0 1775 3846 9337   69 7685]
 [   0    0    0    0 4850 6366 7157 5272]]


In [234]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_sequence_length))
model.compile(optimizer='adam', loss='mse')

h:\AI-ML\Udemy\.venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [235]:
model.summary()

Model: "sequential_22"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_20 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [237]:
embedded_docs[0]

array([   0,    0,    0,    0, 3846, 4777,   69, 3268], dtype=int32)

In [238]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step


array([[[ 0.04595007,  0.02340369,  0.01618988, -0.0467643 ,
         -0.02407062,  0.04095059, -0.04022206,  0.02219169,
          0.04022412,  0.00587786],
        [ 0.04595007,  0.02340369,  0.01618988, -0.0467643 ,
         -0.02407062,  0.04095059, -0.04022206,  0.02219169,
          0.04022412,  0.00587786],
        [ 0.04595007,  0.02340369,  0.01618988, -0.0467643 ,
         -0.02407062,  0.04095059, -0.04022206,  0.02219169,
          0.04022412,  0.00587786],
        [ 0.04595007,  0.02340369,  0.01618988, -0.0467643 ,
         -0.02407062,  0.04095059, -0.04022206,  0.02219169,
          0.04022412,  0.00587786],
        [-0.02281158, -0.00764663, -0.0187287 ,  0.04163703,
          0.049792  , -0.03651184, -0.04187096,  0.02472602,
          0.04329796, -0.04247024],
        [-0.01659817,  0.02699491,  0.02685976,  0.02380823,
          0.04394398,  0.01843214, -0.00088561, -0.0454891 ,
          0.04519433,  0.04027493],
        [-0.02245824,  0.04124136,  0.04882071,  0.0